.local/share/oh-my-zsh:
  type: archive
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.tar.gz
.local/share/oh-my-zsh/custom/plugins/zsh-autosuggestions:
  type: git-repo
  refreshPeriod: 168h
  stripComponents: 1
  url: https://github.com/zsh-users/zsh-autosuggestions
