cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'TylerBrock/saw'

brew 'ack'
brew 'bash-completion'
brew 'coreutils'
brew 'ctags-exuberant'
brew 'gist'
brew 'git'
brew 'git-flow-avh'
brew 'htop'
brew 'jq'
brew 'nmap'
brew 'node'
brew 'openssl'
brew 'terminal-notifier'
brew 'postgresql@9.5'
brew 'terraform'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'watch'
brew 'awscli'
brew 'bash'
brew 'saw'
brew 'go'
brew 'python'

cask 'atom'
cask 'caffeine'
cask 'flux'
cask 'gitter'
cask 'iterm2'
cask 'jing'
cask 'kap'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'ngrok'
cask 'visual-studio-code'
cask 'typora'
